### ISSUE TITLE
18F guides branding: design consistent styles and templates

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#302]
### A description of the work
A clear and concise description of what the work entails.

### Point of contact on this issue
Who can we follow-up with if we have questions?

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [ ] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] What does "done" look like?

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"

**Comment by austinhernandez** [comment]
Coming up with a few different design directions using the USWDS and based on the following guides:

Current Guides on the 18f site
- [Accessibility](https://accessibility.18f.gov/) 
- [Agile](https://agile.18f.gov/) 
- [Content](https://content-guide.18f.gov/) 
- [Derisking](https://derisking-guide.18f.gov/) 
- [Design methods](https://methods.18f.gov/)
- [Engineering](https://engineering.18f.gov/) 
- [Product](https://product-guide.18f.gov/) 
- [User experience ](https://ux-guide.18f.gov/)

Also not listed on the 18F guides site, but listed elsewhere:
- [Handbook also serves as a guide](https://handbook.tts.gsa.gov/)
- [Brand guidelines](https://brand.18f.gov/)
- [18F site style guide](https://18f.gsa.gov/styleguide/)
- [Eng hiring](https://eng-hiring.18f.gov/)


**SCREENSHOTS** (SAME SAME BUT DIFFERENT):
![Image](https://github.com/18F/TLC-crew/assets/23194720/a51fad72-fed9-4955-91bf-4bcd31bc71df)
![Image](https://github.com/18F/TLC-crew/assets/23194720/43807b35-27a7-468f-bf24-c723ec72fd5e)
![Image](https://github.com/18F/TLC-crew/assets/23194720/6e875d7b-a4cd-48cd-bc51-c91e7bbf81ae)
![Image](https://github.com/18F/TLC-crew/assets/23194720/7491184b-c810-4bc5-9b28-5d71e055d05b)
![Image](https://github.com/18F/TLC-crew/assets/23194720/9002e0d5-4ba1-4b76-9d48-2df99a92932a)
![Image](https://github.com/18F/TLC-crew/assets/23194720/d91e34df-7424-4b70-a6f9-499396e5464e)
![Image](https://github.com/18F/TLC-crew/assets/23194720/0ff86503-9f13-45a2-93ba-a1ad2227332c)
![Image](https://github.com/18F/TLC-crew/assets/23194720/658820dc-5ffb-4d90-a8f8-1489fd1ab9c8)
![Image](https://github.com/18F/TLC-crew/assets/23194720/61d4d1a1-c499-44fc-a783-2cb73f60d688)
![Image](https://github.com/18F/TLC-crew/assets/23194720/be83ff54-2aaa-4b88-a343-7ebd5e969cb4)
![Image](https://github.com/18F/TLC-crew/assets/23194720/61d8632c-7684-4fe4-be15-f597d68cb778)

**Comment by austinhernandez** [comment]
For this ticket I compared the differences between the different guides used at 18F. There is not a great deal of difference between 18F guides with the exception of derisking and methods. The guides are essentially the same structure but notable differences in font, spacing, and brand colors. 

**My recommendation is to:**
- update fonts, sizing, spacing, colors, link states, etc. to match [brand guidelines](https://brand.18f.gov/)
   - it doesn't seem as efficient to document every single change on every website if there is also a replatforming as updates might shift the design anyway.
- Go with the most recent, accurate style guide and update the rest to match
- There are a few random differences like anchor link on the product guide is displaying as a `#`, a 🔗  (link icon) on the UX guide, and no anchor link icon on other pages.


**Recommendations for future work:**
- Think more strategically about how guides fit into 18F's mission
   - How can we leverage guides to differentiate from competitors?
   - How can we use guides to extend our 18F brand?
   - How can we use guides to establish ourselves as great partners in technology?
   - How can we continue to raise the bar in civic technology both inside and outside of federal work?
- How can we ensure our users [partners, internal teams, new product teams across government, etc] are getting the most from our guides?
 

**Discussed with @igorkorenfeld and @MelissaBraxton on 6/30. Our resolution:**
- Leave derisking and methods as is with minimal changes such as matching fonts and colors.
- A lot of fixes may be addressed with re-platforming, look at branding and replatforming simultaneously but make fixes afterward
- Since Igor has a lot of experience with 18F branding, it will be more efficient to adjust as he comes across differences 
- Austin to help with questions of color choices and be second set of design eyes 👁 
- Going to add the findings from this ticket to whichever ticket Igor is working on

**Comment by MelissaBraxton** [comment]
Looks great, @austinhernandez! Re: recommendations on future work, I created https://github.com/18F/TLC-crew/issues/314 as a placeholder for you to drop thoughts, but LMK if there's a different way you want to track moving forward with those recommendations!
